services:
  areyouok:
    build: .
    ports:
      - 80:80
    securityContext:
      capabilities:
          add: # 添加
             - SYS_ADMIN
    securityContext:
      privileged: true
          args: ["--device","/dev/fuse"]
